export const ADD_INGREDIENTS = "ADD_INGREDIENTS";
export const GET_ALL_INGREDIENTS = "GET_ALL_INGREDIENTS";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAIL = "GET_INGREDIENTS_FAIL";

export const POST_INGREDIENTS = "POST_INGREDIENTS";
